/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab2;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author ozden
 */
public class PcvsPc extends javax.swing.JFrame {

    /**
     * Creates new form PcvsPc
     */
    public PcvsPc() {
        initComponents();
        iconata();
        vsat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("SCORE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel2.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel3.setText("0");

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("Fight Click");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(288, 288, 288))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (tuşatıklama < 6) {
            do {
                rastgele = yeni.nextInt(3) + 1;
                if (rastgele == 1) {
                    if (tiklama1 < 4) {
                        if (sayac < 10) {
                            jButton1.setIcon(ikon[tut[sayac]]);
                            jButton7.setIcon(ikon[tut[temp1]]);
                            oynayan1=temp1;
                            temp1 = sayac;
                            tiklama1++;
                            sayac++;
                        } else if(sayac>=10){
                            jButton1.setIcon(arkaKapak);
                            jButton7.setIcon(ikon[tut[temp1]]);
                            oynayan1=temp1;
                            tiklama1++;
                            sayac++;
                        }
                     
                        kontrol = 2;
                        
                    }else
                        System.out.println("izgir");
                } else if (rastgele == 2) {
                    if (tiklama2 < 4) {
                        if (sayac < 10) {
                            jButton2.setIcon(ikon[tut[sayac]]);
                            jButton7.setIcon(ikon[tut[temp2]]);
                            oynayan1=temp2;
                            tiklama2++;
                            temp2 = sayac;
                            sayac++;
                        } else if(sayac>=10){
                            jButton2.setIcon(arkaKapak);
                            jButton7.setIcon(ikon[tut[temp2]]);
                            oynayan1=temp2;
                            sayac++;
                            tiklama2++;
                        }
                   
                        kontrol = 2;
                    }else 
                        System.out.println("izgir");
                } else if (rastgele == 3) {
                    if (tiklama3 < 4) {
                        if (sayac < 10) {
                            jButton3.setIcon(ikon[tut[sayac]]);
                            jButton7.setIcon(ikon[tut[temp3]]);
                            oynayan1=temp3;
                            temp3 = sayac;
                            sayac++;
                            tiklama3++;
                        } else if(sayac>=10) {
                            jButton3.setIcon(arkaKapak);
                            jButton7.setIcon(ikon[tut[temp3]]);
                            oynayan1=temp3;
                            tiklama3++;
                            sayac++;
                        }
                    
                        kontrol = 2;
                    }else
                        System.out.println("izgir");
                }
            } while (kontrol == 1);
            kontrol = 1;
            do {
                rastgele = yeni.nextInt(3) + 1;
                if (rastgele == 1) {
                    if (tiklama4 < 4) {
                        if (sayac < 10) {
                            jButton4.setIcon(ikon[tut[sayac]]);
                            jButton8.setIcon(ikon[tut[temp4]]);
                            oynayan2=temp4;
                            temp4 = sayac;
                            tiklama4++;
                            sayac++;
                        } else if(sayac>=10) {
                            jButton4.setIcon(arkaKapak);
                            jButton8.setIcon(ikon[tut[temp4]]);
                            oynayan2=temp4;
                            tiklama4++;
                            sayac++;
                        }
                     
                        kontrol = 2;
                    }else
                        System.out.println("izgir");
                } else if (rastgele == 2) {
                    if (tiklama5 < 4) {
                        if (sayac < 10) {
                            jButton5.setIcon(ikon[tut[sayac]]);
                            jButton8.setIcon(ikon[tut[temp5]]);
                            oynayan2=temp5;
                            tiklama5++;
                            temp5 = sayac;
                            sayac++;
                        } else if(sayac>=10){
                            jButton5.setIcon(arkaKapak);
                            jButton8.setIcon(ikon[tut[temp5]]);
                            oynayan2=temp5;
                            sayac++;
                            tiklama5++;
                        }
                        
                        kontrol = 2;
                    }else 
                        System.out.println("izgir");
                } else if (rastgele == 3) {
                    if (tiklama6 < 4) {
                        if (sayac < 10) {
                            jButton6.setIcon(ikon[tut[sayac]]);
                            jButton8.setIcon(ikon[tut[temp6]]);
                            oynayan2=temp6;
                            temp6 = sayac;
                            sayac++;
                            tiklama6++;
                        } else if(sayac>=10){
                            jButton6.setIcon(arkaKapak);
                            jButton8.setIcon(ikon[tut[temp6]]);
                            tiklama6++;
                            oynayan2=temp6;
                            sayac++;
                        }
                        kontrol = 2;
                        
                       
                    }else 
                        System.out.println("izgir");
                }
                if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel2.setText("" + puanPlayer);
            jLabel3.setText("" + puanPc);
            } while (kontrol == 1);
            kontrol = 1;
            tuşatıklama++;
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PcvsPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PcvsPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PcvsPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PcvsPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PcvsPc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    ImageIcon[] ikon = new ImageIcon[10];
    Random yeni = new Random();
    int[] tut = new int[10];
    int[] hasar = new int[10];
    int sayac = 6, tiklama1 = 1, tiklama2 = 1, tiklama3 = 1, tiklama4 = 1, tiklama5 = 1, tiklama6 = 0, temp1 = 0, temp2 = 1, temp3 = 2, temp4 = 3, temp5 = 4, temp6 = 5, sıra = 2;
    int puanPc = 0, puanPlayer = 0;
    int oynayan1, oynayan2;
    int tıklama, rastgele, kontrol = 1, elkontrol = 1, tuşatıklama = 1;

    private void iconata() {
        Bulbasaur bulba = new Bulbasaur();
        Butterfree butter = new Butterfree();
        Charmander charm = new Charmander();
        Jigglypuff jig = new Jigglypuff();
        Meowth meow = new Meowth();
        Pikachu pika = new Pikachu();
        Psyduck psy = new Psyduck();
        Snorlax snor = new Snorlax();
        Squirtle squir = new Squirtle();
        Zubat zub = new Zubat();

        int sayi = yeni.nextInt(10);
        tut[0] = sayi;
        for (int i = 1; i < tut.length; i++) {
            sayi = yeni.nextInt(10);
            for (int j = 0; j < i; j++) {
                if (tut[j] == sayi) {
                    i--;
                    break;
                } else {
                    tut[i] = sayi;
                }

            }
        }

        ikon[0] = bulba.getIkon();
        hasar[0] = bulba.getHasarPuani();
        ikon[1] = butter.getIkon();
        hasar[1] = butter.getHasarPuani();
        ikon[2] = charm.getIkon();
        hasar[2] = charm.getHasarPuani();
        ikon[3] = jig.getIkon();
        hasar[3] = jig.getHasarPuani();
        ikon[4] = meow.getIkon();
        hasar[4] = meow.getHasarPuani();
        ikon[5] = pika.getIkon();
        hasar[5] = pika.getHasarPuani();
        ikon[6] = psy.getIkon();
        hasar[6] = psy.getHasarPuani();
        ikon[7] = snor.getIkon();
        hasar[7] = snor.getHasarPuani();
        ikon[8] = squir.getIkon();
        hasar[8] = squir.getHasarPuani();
        ikon[9] = zub.getIkon();
        hasar[9] = bulba.getHasarPuani();

        jButton1.setIcon(ikon[tut[0]]);
        jButton2.setIcon(ikon[tut[1]]);
        jButton3.setIcon(ikon[tut[2]]);
        jButton4.setIcon(ikon[tut[3]]);
        jButton5.setIcon(ikon[tut[4]]);
        jButton6.setIcon(ikon[tut[5]]);
    }
    ImageIcon arkaKapak = new ImageIcon("Arkakapak.jpg");

    private void vsat() {

    }
}
