/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab2;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author ozden
 */
public class PcvsPlayer extends javax.swing.JFrame {

    /**
     * Creates new form PcvsPlayer
     */
    public PcvsPlayer() {
        this.ikon = new ImageIcon[10];
        initComponents();
        iconata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Player");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Computer");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText("Points");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(387, 387, 387)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(97, 97, 97)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 367, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (tiklama4 == 1 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp4]]);
                jLabel4.setText("Power:" + hasar[tut[temp4]]);
                oynayan2 = temp4;
                temp4 = sayac;
                jButton4.setIcon(ikon[tut[sayac++]]);
                tiklama4++;

            } else {
                jButton4.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp4]]);
                oynayan2 = temp4;
                jLabel4.setText("Power:" + hasar[tut[temp4]]);
            }
            sıra++;
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama4=2;
        } else if (tiklama4 == 2 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp4]]);
                jLabel4.setText("Power:" + hasar[tut[temp4]]);
                oynayan2 = temp4;
                temp4 = sayac;
                jButton4.setIcon(ikon[tut[sayac++]]);
                tiklama4++;

            } else {
                jButton4.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp4]]);
                oynayan2 = temp4;
                jLabel4.setText("Power:" + hasar[tut[temp4]]);
            }
            sıra++;
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama4=3;
        } else if (tiklama4 == 3 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp4]]);
                jLabel4.setText("Power:" + hasar[tut[temp4]]);
                oynayan2 = temp4;
                temp4 = sayac;
                jButton4.setIcon(ikon[tut[sayac++]]);
                tiklama4++;

            } else {
                jButton4.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp4]]);
                oynayan2 = temp4;
                jLabel4.setText("Power:" + hasar[tut[temp4]]);
            }
            sıra++;
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama4=4;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tiklama3 == 1 && sıra % 2 == 0 && elkontrol < 6) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp3]]);
                jLabel3.setText("Power:" + hasar[tut[temp3]]);
                oynayan1 = temp3;

                temp3 = sayac;
                jButton3.setIcon(ikon[tut[sayac++]]);
                tiklama3++;
                sıra++;
                rastgele = yeni.nextInt(3) + 1;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton3.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp3]]);
                oynayan1 = temp3;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp3]]);

                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;
                
            }
            tiklama3=2;    
        } else if (tiklama3 == 2 && sıra % 2 == 0 && elkontrol < 6) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp3]]);
                jLabel3.setText("Power:" + hasar[tut[temp3]]);
                oynayan1 = temp3;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp3 = sayac;
                jButton3.setIcon(ikon[tut[sayac++]]);
                tiklama3++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton3.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp3]]);
                oynayan1 = temp3;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp3]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama3=3;
        } else if (tiklama3 == 3 && sıra % 2 == 0 && elkontrol < 6) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp3]]);
                jLabel3.setText("Power:" + hasar[tut[temp3]]);
                oynayan1 = temp3;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp3 = sayac;
                jButton3.setIcon(ikon[tut[sayac++]]);
                tiklama3++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton3.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp3]]);
                oynayan1 = temp3;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp3]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama3=4;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((tiklama1 == 1) && (sıra % 2 == 0) && (elkontrol < 6)) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp1]]);
                jLabel3.setText("Power:" + hasar[tut[temp1]]);
                oynayan1 = temp1;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp1 = sayac;
                jButton1.setIcon(ikon[tut[sayac++]]);
                tiklama1++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton1.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp1]]);
                oynayan1 = temp1;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp1]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama1=2;
        } else if ((tiklama1 == 2) && (sıra % 2 == 0) && (elkontrol < 6)) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp1]]);
                jLabel3.setText("Power:" + hasar[tut[temp1]]);
                oynayan1 = temp1;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp1 = sayac;
                jButton1.setIcon(ikon[tut[sayac++]]);
                tiklama1++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton1.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp1]]);
                oynayan1 = temp1;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp1]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama1=3;
        } else if ((tiklama1 == 3) && (sıra % 2 == 0) && (elkontrol < 6)) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp1]]);
                jLabel3.setText("Power:" + hasar[tut[temp1]]);
                oynayan1 = temp1;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp1 = sayac;
                jButton1.setIcon(ikon[tut[sayac++]]);
                tiklama1++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton1.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp1]]);
                oynayan1 = temp1;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp1]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama1=4;
        }else{
            System.out.println("evren");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tiklama2 == 1 && sıra % 2 == 0 && elkontrol< 6) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp2]]);
                jLabel3.setText("Power:" + hasar[tut[temp2]]);
                oynayan1 = temp2;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp2 = sayac;
                jButton2.setIcon(ikon[tut[sayac++]]);
                tiklama2++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton2.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp2]]);
                oynayan1 = temp2;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp2]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama2=2;
        } else if (tiklama2 == 2 && sıra % 2 == 0 && elkontrol < 6) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp2]]);
                jLabel3.setText("Power:" + hasar[tut[temp2]]);
                oynayan1 = temp2;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp2 = sayac;
                jButton2.setIcon(ikon[tut[sayac++]]);
                tiklama2++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton2.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp2]]);
                oynayan1 = temp2;

                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp2]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama2=3;
        } else if (tiklama2 == 3 && sıra % 2 == 0 && elkontrol < 6) {
            if (sayac < 10) {
                jButton7.setIcon(ikon[tut[temp2]]);
                jLabel3.setText("Power:" + hasar[tut[temp2]]);
                oynayan1 = temp2;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                temp2 = sayac;
                jButton2.setIcon(ikon[tut[sayac++]]);
                tiklama2++;
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            } else {
                jButton2.setIcon(arkaKapak);
                jButton7.setIcon(ikon[tut[temp2]]);
                oynayan1 = temp2;
                rastgele = yeni.nextInt(3) + 1;
                sıra++;
                jLabel3.setText("Power:" + hasar[tut[temp2]]);
                do {
                    if (rastgele == 1) {
                        if (tiklama4 < 4) {
                            jButton4.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 2) {
                        if (tiklama5 < 4) {
                            jButton5.doClick();
                            kontrol = 2;
                        }
                    } else if (rastgele == 3) {
                        if (tiklama6 < 4) {
                            jButton6.doClick();
                            kontrol = 2;
                        }
                    }
                        rastgele = yeni.nextInt(3) + 1;                    
                } while (kontrol == 1);
                kontrol = 1;

            }
            tiklama2=4;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (tiklama5 == 1 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp5]]);
                jLabel4.setText("Power:" + hasar[tut[temp5]]);
                oynayan2 = temp5;
                temp5 = sayac;
                jButton5.setIcon(ikon[tut[sayac++]]);
                tiklama5++;
                sıra++;
            } else {
                jButton5.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp5]]);
                oynayan2 = temp5;
                jLabel4.setText("Power:" + hasar[tut[temp5]]);
                sıra++;
                jLabel5.setText("" + puanPlayer);
                jLabel6.setText("" + puanPc);
            }
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama5=2;
        } else if (tiklama5 == 2 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp5]]);
                jLabel4.setText("Power:" + hasar[tut[temp5]]);
                oynayan2 = temp5;
                temp5 = sayac;
                jButton5.setIcon(ikon[tut[sayac++]]);
                tiklama5++;
                sıra++;
            } else {
                jButton5.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp5]]);
                oynayan2 = temp5;
                jLabel4.setText("Power:" + hasar[tut[temp5]]);
                sıra++;
            }
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama5=3;
        } else if (tiklama5 == 3 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp5]]);
                jLabel4.setText("Power:" + hasar[tut[temp5]]);
                oynayan2 = temp5;
                temp5 = sayac;
                jButton5.setIcon(ikon[tut[sayac++]]);
                tiklama5++;
                sıra++;
            } else {
                jButton5.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp2]]);
                oynayan2 = temp5;
                jLabel4.setText("Power:" + hasar[tut[temp5]]);
                sıra++;
            }
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);

            elkontrol++;
            tiklama5=4;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (tiklama6 == 1 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp6]]);
                jLabel4.setText("Power:" + hasar[tut[temp6]]);
                oynayan2 = temp6;
                temp6 = sayac;
                jButton6.setIcon(ikon[tut[sayac++]]);
                tiklama6++;
                sıra++;
            } else {
                jButton6.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp6]]);
                oynayan2 = temp6;
                jLabel4.setText("Power:" + hasar[tut[temp6]]);
                sıra++;
            }
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama6=2;
        } else if (tiklama6 == 2 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp6]]);
                jLabel4.setText("Power:" + hasar[tut[temp6]]);
                oynayan2 = temp6;
                temp6 = sayac;
                jButton6.setIcon(ikon[tut[sayac++]]);
                tiklama6++;
                sıra++;
            } else {
                jButton6.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp6]]);
                oynayan2 = temp6;
                jLabel4.setText("Power:" + hasar[tut[temp6]]);
                sıra++;
            }
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama6=3;
        } else if (tiklama6 == 3 && sıra % 2 == 1 && elkontrol < 6) {
            if (sayac < 10) {
                jButton8.setIcon(ikon[tut[temp6]]);
                temp6 = sayac;
                jButton6.setIcon(ikon[tut[sayac++]]);
                oynayan2 = temp6;
                jLabel4.setText("Power:" + hasar[tut[temp6]]);
                tiklama6++;
                sıra++;
            } else {
                jButton6.setIcon(arkaKapak);
                jButton8.setIcon(ikon[tut[temp6]]);
                oynayan2 = temp6;
                jLabel4.setText("Power:" + hasar[tut[temp6]]);
                sıra++;
            }
            if (hasar[tut[oynayan1]] > hasar[tut[oynayan2]]) {
                puanPlayer += 5;
            } else if (hasar[tut[oynayan1]] < hasar[tut[oynayan2]]) {
                puanPc += 5;
            }
            jLabel5.setText("" + puanPlayer);
            jLabel6.setText("" + puanPc);
            elkontrol++;
            tiklama6=4;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PcvsPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PcvsPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PcvsPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PcvsPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PcvsPlayer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    ImageIcon[] ikon = new ImageIcon[10];
    ImageIcon arkaKapak = new ImageIcon("Arkakapak.jpg");

    int[] tut = new int[10];
    int[] hasar = new int[10];
    int sayac = 6, tiklama1 = 1, tiklama2 = 1, tiklama3 = 1, tiklama4 = 1, tiklama5 = 1, tiklama6 = 1, temp1 = 0, temp2 = 1, temp3 = 2, temp4 = 3, temp5 = 4, temp6 = 5, sıra = 2;
    int puanPc = 0, puanPlayer = 0;
    int oynayan1, oynayan2;
    int rastgele, kontrol = 1, elkontrol = 1;
    InsanOyuncusu player = new InsanOyuncusu();
    BilgisayarOyuncusu pc = new BilgisayarOyuncusu();

    Random yeni = new Random();

    private void iconata() {
        /*ikon[0] = new ImageIcon("Bulbasaur.png");
         ikon[1] = new ImageIcon("Butterfree.png");
         ikon[2] = new ImageIcon("Charmander.png");
         ikon[3] = new ImageIcon("Jigglypuff.png");
         ikon[4] = new ImageIcon("Meowth.png");
         ikon[5] = new ImageIcon("Pikachu.png");
         ikon[6] = new ImageIcon("Psyduck.png");
         ikon[7] = new ImageIcon("Snorlax.png");
         ikon[8] = new ImageIcon("Squirtle.png");
         ikon[9] = new ImageIcon("Zubat.png");*/
        Bulbasaur bulba = new Bulbasaur();
        Butterfree butter = new Butterfree();
        Charmander charm = new Charmander();
        Jigglypuff jig = new Jigglypuff();
        Meowth meow = new Meowth();
        Pikachu pika = new Pikachu();
        Psyduck psy = new Psyduck();
        Snorlax snor = new Snorlax();
        Squirtle squir = new Squirtle();
        Zubat zub = new Zubat();

        int sayi = yeni.nextInt(10);
        tut[0] = sayi;
        for (int i = 1; i < tut.length; i++) {
            sayi = yeni.nextInt(10);
            for (int j = 0; j < i; j++) {
                if (tut[j] == sayi) {
                    i--;
                    break;
                } else {
                    tut[i] = sayi;
                }

            }
        }

        ikon[0] = bulba.getIkon();
        hasar[0] = bulba.getHasarPuani();
        ikon[1] = butter.getIkon();
        hasar[1] = butter.getHasarPuani();
        ikon[2] = charm.getIkon();
        hasar[2] = charm.getHasarPuani();
        ikon[3] = jig.getIkon();
        hasar[3] = jig.getHasarPuani();
        ikon[4] = meow.getIkon();
        hasar[4] = meow.getHasarPuani();
        ikon[5] = pika.getIkon();
        hasar[5] = pika.getHasarPuani();
        ikon[6] = psy.getIkon();
        hasar[6] = psy.getHasarPuani();
        ikon[7] = snor.getIkon();
        hasar[7] = snor.getHasarPuani();
        ikon[8] = squir.getIkon();
        hasar[8] = squir.getHasarPuani();
        ikon[9] = zub.getIkon();
        hasar[9] = bulba.getHasarPuani();

        jButton1.setIcon(ikon[tut[0]]);
        jButton2.setIcon(ikon[tut[1]]);
        jButton3.setIcon(ikon[tut[2]]);
        jButton4.setIcon(ikon[tut[3]]);
        jButton5.setIcon(ikon[tut[4]]);
        jButton6.setIcon(ikon[tut[5]]);

    }

}
